version: '3.4'

networks:
  backend:

services:
  userdb:
    container_name: user-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8001:1433 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend

  productdb:
    container_name: product-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8003:1433 
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password@12345#
    networks:
        - backend

  usermanagement:
    container_name: user-api
    image: ${DOCKER_REGISTRY-}usermanagement
    build:
      context: .
      dockerfile: UserManagement/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=userdb
      - DB_NAME=user
      - DB_SA_PASSWORD=password@12345#

  productmanagement:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productmanagement
    build:
      context: .
      dockerfile: ProductManagement/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=productdb
      - DB_NAME=product
      - DB_SA_PASSWORD=password@12345#


  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - 8001:80
    networks:
      - backend

