version: '3.4'

networks:
  backend:

services:
  userdb:
    container_name: user-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8001:1433 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
  usermanagement:
    container_name: user-api
    image: ${DOCKER_REGISTRY-}usermanagement
    build:
      context: .
      dockerfile: UserManagement/Dockerfile
    networks:
      - backend
    ports:
      - 8002:80
    environment:
      - DB_HOST=userdb
      - DB_NAME=user
      - DB_SA_PASSWORD=password@12345#
